### PR TITLE
Fox: I fixed all the indentations (the structure still same just fix the indentation)

### PR DESCRIPTION
**Pull request by NickWilde263**
Also i found <body> missing in one of the html files only the </body> exist

### CODE REVIEW

**Review by PutoPug — APPROVED** [review]
Approved

**Review by PutoPug — APPROVED** [review]
Approved.

**Review by Cy4Shot — APPROVED** [review]

**Review by BinaryBytes772 — APPROVED** [review]
Looks fine, just fixed pug's indentation

**Comment by NickWilde263** [comment]
> Looks fine, just fixed pug's indentation

i bulk commit it to my fork using copy paste

**Pull request merged**
